//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public int id { get; set; }
        public float amount { get; set; }
        public System.DateTime time { get; set; }
        public string type { get; set; }
        public bool recur { get; set; }
        public int transactionSourceId { get; set; }
    }
}
