//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entitites
{
    using System;
    using System.Collections.Generic;
    
    public partial class recurrence
    {
        public int id { get; set; }
        public string frequency { get; set; }
        public int transactionId { get; set; }
        public System.DateTime updatedDate { get; set; }
    }
}
