//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeTransaction
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public short IncomeSourceId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> Monthy { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
